kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .ApplicationName }}
  name: {{ .GiteaDeploymentName }}
  namespace: {{ .ApplicationNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .ApplicationName }}
      deployment: {{ .ApplicationName }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .ApplicationName }}
        deployment: {{ .GiteaDeploymentName }}
    spec:
      serviceAccountName: {{ .GiteaServiceAccountName }}
      containers:
      - image: "{{ .GiteaImage }}:{{ .GiteaVersion }}"
        imagePullPolicy: Always
        name: {{ .ApplicationName }}
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: {{ .GiteaReposPvcName }}
          mountPath: /gitea-repositories
        - name: {{ .GiteaConfigMapName }}
          mountPath: /home/gitea/conf
        readinessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 20
            successThreshold: 1
            failureThreshold: 3
        livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: {{ .GiteaReposPvcName }}
        persistentVolumeClaim:
          claimName: {{ .GiteaReposPvcName }}
      - name: {{ .GiteaConfigMapName }}
        configMap:
          name: {{ .GiteaConfigMapName }}
          items:
            - key: app.ini
              path: app.ini
  test: false
  triggers:
  - type: ConfigChange