kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .GiteaConfigMapName }}
  namespace: {{ .ApplicationNamespace }}
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_USER = gitea
    RUN_MODE = prod

    [security]
    INTERNAL_TOKEN = {{ .GiteaInternalToken }}
    INSTALL_LOCK   = true
    SECRET_KEY     = {{ .GiteaSecretKey }}

    [database]
    DB_TYPE  = postgres
    HOST     = {{ .GiteaPgServiceName }}:5432
    NAME     = {{ .DatabaseName }}
    USER     = {{ .DatabaseUser }}
    PASSWD   = {{ .DatabasePassword }}
    SSL_MODE = disable
    PATH     = data/gitea.db

    [repository]
    ROOT = /gitea-repositories

    [server]
    SSH_DOMAIN       = {{ .Hostname }}
    DOMAIN           = {{ .Hostname }}
    HTTP_PORT        = 3000
    SSH_PORT         = 2022
    ROOT_URL         = http://{{ .Hostname }}
    DISABLE_SSH      = false
    START_SSH_SERVER = true
    LFS_START_SERVER = false
    OFFLINE_MODE     = false

    [mailer]
    ENABLED = false

    [service]
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    DISABLE_REGISTRATION              = false
    ENABLE_CAPTCHA                    = false
    REQUIRE_SIGNIN_VIEW               = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org

    [picture]
    DISABLE_GRAVATAR        = false
    ENABLE_FEDERATED_AVATAR = true

    [openid]
    ENABLE_OPENID_SIGNIN = false
    ENABLE_OPENID_SIGNUP = false

    [session]
    PROVIDER = file

    [log]
    MODE      = file
    LEVEL     = Trace
    ROOT_PATH = /home/gitea/log

    [markup.asciidoc]
    ENABLED = true
    FILE_EXTENSIONS = .adoc,.asciidoc
    RENDER_COMMAND = "asciidoc --out-file=- -"
    IS_INPUT_FILE = false