kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .GiteaPgPvcName }}
  namespace: {{ .ApplicationNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .DbVolumeCapacity }}
