apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .ProxyDeploymentName }}
  namespace: {{ .ApplicationNamespace }}
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: {{ .ProxyServiceAccountName }}
      containers:
      - name: oauth-proxy
        image: openshift/oauth-proxy:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: public
        args:
          - '--provider=openshift'
          - '--openshift-service-account={{ .ProxyServiceAccountName }}'
          - '--upstream=http://{{ .GiteaServiceName }}:3000'
          - '--cookie-secret=SECRET'
          - '--http-address=0.0.0.0:8080'
          - '--https-address='
          - '--skip-provider-button'
          - '--skip-auth-regex=/logout'
          - '--skip-auth-regex=/[^/]+\.(png|jpg|eot|svg|ttf|woff|woff2)'
          - '--skip-auth-preflight'
          - '--pass-user-headers'