apiVersion: v1
kind: Service
metadata:
  name: {{ .ProxyServiceName }}
  namespace: {{ .ApplicationNamespace }}
spec:
  ports:
  - name: proxy
    port: 8080
    targetPort: 8080
  selector:
    app: proxy